services:
  appDb:
    image: bitnami/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db2hf
    ports:
      - 3306:3306
    volumes:
      # - './data:/bitnami/mysql/data'
      - "./initdb:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-password", "-e", "show schemas"]
      interval: 10s

  2hf:
    build: .
    restart: always
    depends_on:
      appDb:
        condition: service_healthy
    environment:
      HTTP_PORT: 8080
      CONNECTION_STRING: root:password@tcp(appDb:3306)/db2hf?charset=utf8&parseTime=True&loc=Local
      STORAGE: db
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    ports: # host:container
      - 8081:8080
